---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: localingress-ds
  namespace: localingress
  labels:
    component: localingress
spec:
  selector:
    matchLabels:
      component: localingress
  template:
    metadata:
      labels:
        component: localingress
    spec:
      volumes:
        - name: localingress-config
          configMap:
            name: localingress-config
      containers:
        - name: ingress
          image: docker.io/library/haproxy:2.7.1
          env:
            - name: INGRESS_HOST
              value: "ingress-nginx-controller.ingress-nginx.svc.cluster.local"
          volumeMounts:
            - name: localingress-config
              mountPath: "/usr/local/etc/haproxy/"
          ports:
            - containerPort: 8443
              hostPort: 443
            - containerPort: 8080
              hostPort: 80
