---
resources:
  - daemonset.yaml

configurations:
  - config.yaml

commonLabels:
  app: localingress
namespace: localingress

generatorOptions:
  labels:
    app: localingress

configMapGenerator:
  - name: localingress-config
    files:
      - haproxy.cfg=config/localingress.cfg
